import type { Metadata } from 'next';
import { Source_Sans_3, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import MenuBar from './menubar';

const sourceSansPro = Source_Sans_3({
  variable: '--font-source-sans-pro',
  subsets: ['latin'],
});

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSansPro.variable} ${jetBrainsMono.variable} antialiased`}>
        <MenuBar />
        {children}
      </body>
    </html>
  );
}
