import type { Metadata } from 'next';
import { JetBrains_Mono, Source_Sans_3 } from 'next/font/google';

import { ThemeProvider } from '@/components/providers/theme-provider';

import MenuBar from '../components/menubar';
import Sidebar from '../components/sidebar';
import './globals.css';

const sourceSansPro = Source_Sans_3({
  variable: '--font-source-sans-pro',
  subsets: ['latin']
});

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${sourceSansPro.variable} ${jetBrainsMono.variable} grid h-dvh grid-rows-[auto_1fr] antialiased`}>
        <ThemeProvider>
          <MenuBar />
          <Sidebar>{children}</Sidebar>
        </ThemeProvider>
      </body>
    </html>
  );
}
